sudo: required
language: python

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account-050e0daf33a3.json.enc -out service-account-050e0daf33a3.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account-050e0daf33a3.json
  - gcloud config set project gym-hero-results
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials gym-hero-cluster
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t mikemcgarry/canary-bird_cage-test -f ./bird_cage/Dockerfile.dev ./bird_cage
  - docker build -t mikemcgarry/canary-silence-test -f ./silence/Dockerfile.dev ./silence

script:
  -  |

    if [ "$TRAVIS_BRANCH" = "master" ]; then
      TWILIO_ACCOUNT_ID="TWILIO_ACCOUNT_ID_CI"
      TWILIO_AUTH_TOKEN="TWILIO_AUTH_TOKEN_CI"
      AWS_SERVER_PUBLIC_KEY_LOGS="AWS_SERVER_PUBLIC_KEY_LOGS_CI"
      AWS_SERVER_SECRET_KEY_LOGS="AWS_SERVER_SECRET_KEY_LOGS_CI"
      AWS_SERVER_PUBLIC_KEY_ATHENA="AWS_SERVER_PUBLIC_KEY_ATHENA_CI"
      AWS_SERVER_SECRET_KEY_ATHENA="AWS_SERVER_SECRET_KEY_ATHENA_CI"
      SUBSCRIBERS_QUERY_RESULTS_S3_BUCKET_NAME="SUBSCRIBERS_QUERY_RESULTS_S3_BUCKET_NAME_CI"
      POLLUTION_QUERY_RESULTS_S3_BUCKET_NAME="POLLUTION_QUERY_RESULTS_S3_BUCKET_NAME_CI"
      POLLUTION_DATABASE_NAME="POLLUTION_DATABASE_NAME_CI"
      NOTIFICATION_LOGS_S3_BUCKET_NAME="NOTIFICATION_LOGS_S3_BUCKET_NAME_CI"
      POLLUTION_OUTPUT_NAME="POLLUTION_OUTPUT_NAME_CI"
      SUBSCRIBERS_OUTPUT_NAME="SUBSCRIBERS_OUTPUT_NAME_CI"
      AWS_REGION="AWS_REGION_CI"

    else
      TWILIO_ACCOUNT_ID="TWILIO_ACCOUNT_ID_CI"
      TWILIO_AUTH_TOKEN="TWILIO_AUTH_TOKEN_CI"
      AWS_SERVER_PUBLIC_KEY_LOGS="AWS_SERVER_PUBLIC_KEY_LOGS_CI"
      AWS_SERVER_SECRET_KEY_LOGS="AWS_SERVER_SECRET_KEY_LOGS_CI"
      AWS_SERVER_PUBLIC_KEY_ATHENA="AWS_SERVER_PUBLIC_KEY_ATHENA_CI"
      AWS_SERVER_SECRET_KEY_ATHENA="AWS_SERVER_SECRET_KEY_ATHENA_CI"
      SUBSCRIBERS_QUERY_RESULTS_S3_BUCKET_NAME="SUBSCRIBERS_QUERY_RESULTS_S3_BUCKET_NAME_CI"
      POLLUTION_QUERY_RESULTS_S3_BUCKET_NAME="POLLUTION_QUERY_RESULTS_S3_BUCKET_NAME_CI"
      POLLUTION_DATABASE_NAME="POLLUTION_DATABASE_NAME_CI"
      NOTIFICATION_LOGS_S3_BUCKET_NAME="NOTIFICATION_LOGS_S3_BUCKET_NAME_CI"
      POLLUTION_OUTPUT_NAME="POLLUTION_OUTPUT_NAME_CI"
      SUBSCRIBERS_OUTPUT_NAME="SUBSCRIBERS_OUTPUT_NAME_CI"
      AWS_REGION="AWS_REGION_CI"
    fi

    docker run -e CI=true mikemcgarry/canary-bird_cage-test npm test -- --coverage

    docker run \
      -e TWILIO_ACCOUNT_ID=${!TWILIO_ACCOUNT_ID} \
      -e TWILIO_AUTH_TOKEN=${!TWILIO_AUTH_TOKEN} \
      -e AWS_SERVER_PUBLIC_KEY_LOGS=${!AWS_SERVER_PUBLIC_KEY_LOGS} \
      -e AWS_SERVER_SECRET_KEY_LOGS=${!AWS_SERVER_SECRET_KEY_LOGS} \
      -e AWS_SERVER_PUBLIC_KEY_ATHENA=${!AWS_SERVER_PUBLIC_KEY_ATHENA} \
      -e AWS_SERVER_SECRET_KEY_ATHENA=${!AWS_SERVER_SECRET_KEY_ATHENA} \
      -e SUBSCRIBERS_QUERY_RESULTS_S3_BUCKET_NAME=${!SUBSCRIBERS_QUERY_RESULTS_S3_BUCKET_NAME} \
      -e POLLUTION_QUERY_RESULTS_S3_BUCKET_NAME=${!POLLUTION_QUERY_RESULTS_S3_BUCKET_NAME} \
      -e POLLUTION_DATABASE_NAME=${!POLLUTION_DATABASE_NAME} \
      -e NOTIFICATION_LOGS_S3_BUCKET_NAME=${!NOTIFICATION_LOGS_S3_BUCKET_NAME} \
      -e POLLUTION_OUTPUT_NAME=${!POLLUTION_OUTPUT_NAME} \
      -e SUBSCRIBERS_OUTPUT_NAME=${!SUBSCRIBERS_OUTPUT_NAME} \
      -e AWS_REGION=${!AWS_REGION} \
      mikemcgarry/canary-silence-test

deploy:
  - provider: script
    script: bash ./deploy.sh canary
    on:
      branch: master
  - provider: script
    script: bash ./deploy.sh canary-ci
    on:
      branch: develop
