apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller-deployment
spec:
  # Number of pods to create and manage
  replicas: 1
  # Allows deployment to get handle on created pods
  selector:
    matchLabels:
      component: notification
  # The pod configurationm same as in a Pod config file
  template:
    metadata:
      labels:
        component: notification
    spec:
      containers:
        - name: silence
          image: mikemcgarry/canary-silence
          volumeMounts:
            - name: data
              mountPath: /tmp/silence/data
          env:
            - name: TWILIO_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: twilio
                  key: ACCOUNT_ID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio
                  key: AUTH_TOKEN
        - name: feathers
          image: mikemcgarry/canary-feathers
          volumeMounts:
            - name: data
              mountPath: /tmp/feathers/data
          env:
            - name: AWS_SERVER_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: aws.athena
                  key: SERVER_PUBLIC_KEY
            - name: AWS_SERVER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws.athena
                  key: SERVER_SECRET_KEY
      volumes:
        - name: data
          emptyDir: {}
